version: '3'
services:
  # Database - Mongo DB
  mongo:
    image: mongo:8.0.3
    container_name: chat_db
    restart: always
    environment:
      DATABASE_ROOT_USERNAME: ${DATABASE_ROOT_USERNAME}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - 27017:${DATABASE_PORT}
    env_file:
      - path: .env
    volumes:
      # - ./mongodb-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
